### ISSUE TITLE
直接進入 en 時版會爛掉

### ISSUE THREAD

**Issue by ryudoawaru** [5xRuby/5xruby.tw#14]
重現步驟：

-  直接在網址列輸入：http://5xruby.tw/en

![2015-11-20 11 45 51](https://cloud.githubusercontent.com/assets/212290/11291523/43852452-8f7c-11e5-92d9-8b285129287f.png)

如果先進沒 en 再點 English 則不會發生這個問題

**Comment by KazooTang** [comment]
我這邊看不到這個問題＠＠

**Comment by kaochenlong** [comment]
LGTM
