### ISSUE TITLE
h2 未設置，頁面設置 3個包含關鍵字的 h2

### ISSUE THREAD

**Issue by a25416099** [5xRuby/5xruby.tw#99]
## **需求：佔照不同網頁，於頁面設置3個包含關鍵字的** h2

解釋：為了幫助 Google 判斷該頁面是什麼課程，針對不同課程頁面請設置 h2 帶出不同關鍵字

目前課前頁面有以下三頁
初心者網站架構入門班
### h2 關鍵字：前端網頁開發 . 入門課程 . HTML
https://5xruby.tw/camps/camp-junior-201708

網頁前端設計女性專班
### h2 關鍵字：前端工程師 . CSS . 女性專班
https://5xruby.tw/camps/camp-girl-2017

全方位衝刺班
### h2 關鍵字：GIT . Ruby on Rails . 面試
https://5xruby.tw/camps/camp2018-1

**Comment by ryudoawaru** [comment]
@ringo636  @elct9620 覺得 h2 要插哪裡？

**Comment by elct9620** [comment]
要看頁面內容，這頁 h2 應該是課程 Timeline 的課程標題吧。

**Comment by ryudoawaru** [comment]
等一下 小M的意思應該是要加關鍵字 所以到底是要加在哪？

**Comment by elct9620** [comment]
一般課程名稱就是包含關鍵字的狀態，然後至少要有三個。

**Comment by ryudoawaru** [comment]
先把衝刺班的課程名稱頁改成 h2 了，大小有點變化請 @ringo636 看要怎麼調，可以在下面回就好了

<img width="696" alt="screen shot 2018-03-15 at 5 53 03 pm" src="https://user-images.githubusercontent.com/212290/37456200-d1f114d8-2879-11e8-93f3-b3e208ea8833.png">
